version: 0.2

phases:
  install:
    commands:
      - npm install -g dotnet
  pre_build:
    commands:
      - dotnet --version
  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - echo Build completed on `date`